### ISSUE TITLE
 illegal opcodes

### ISSUE THREAD

**Issue by XadNightfall** [iPodLinux-Community/TinySID#3]
Hi all,

This is a very good project, i have no chance that anyone will add the support for illegal opcodes :D , in particular LAX (OPCODE: A7) which is used in the LUNATICO sid tune.

https://csdb.dk/sid/?id=53592

**Comment by Keripo** [comment]
I am not familiar with TinySID or SID itself, but here's the beauty of open source... if there's something you want, you have the option to add it yourself! (and if it works, make a pull request to contribute back so others can enjoy it as well)
